site_name: Ken Jenney
theme:
  name: readthedocs
  favicon: images/favicon.png
plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: false
      nav_repos:
        - name: resume
          import_url: https://github.com/kjenney/myresume?branch=main
          imports: [
            docs/certifications.md, docs/education.md, docs/index.md, docs/experience.md, docs/skills.md
            # asset files needed
            # docs/assets/*
            ]
        - name: fast-api
          import_url: https://github.com/tiangolo/fastapi
          imports: [docs/en/docs/index.md]

nav:
  - Resume:
      - Home: resume/docs/index.md
      - Certifications: resume/docs/certifications.md
      - Education: resume/docs/education.md
      - Experience: resume/docs/experience.md
      - Skills: resume/docs/skills.md