site_name: Ken Jenney
site_url: https://kenjenney.com
site_author: Ken Jenney
site_description: All kinds of stuff about Ken Jenney

# Repository
repo_name: kjenney/kenjenney.github.io
repo_url: https://github.com/kjenney/kenjenney.github.io

# Copyright
copyright: Copyright &copy; 2024 Ken Jenney

theme:
  name: material
  favicon: assets/me.png
  logo: assets/me.png
  features:
    - announce.dismiss
    - navigation.top
    - search.highlight
    - search.suggest
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: false
      nav_repos:
        - name: resume
          import_url: https://github.com/kjenney/myresume?branch=main
          imports: [
            docs/certifications.md, docs/education.md, docs/contact.md, docs/experience.md, docs/skills.md
            # asset files needed
            # docs/assets/*
            ]
        - name: tgw-tester
          import_url: https://github.com/kjenney/terraform-aws-tgw-tester?branch=main
          imports: [docs/index.md]
        - name: ai
          import_url: https://github.com/kjenney/ai-resources?branch=main
          imports: [docs/index.md]

nav:
  - Home: index.md
  - Resume:
      - Contact Info: resume/docs/contact.md
      - Certifications: resume/docs/certifications.md
      - Education: resume/docs/education.md
      - Experience: resume/docs/experience.md
      - Skills: resume/docs/skills.md
  - Projects:
      - Terraform:
        - AWS Transit Gateway Tester: tgw-tester/docs/index.md
  - Hobbies: 
      - hobbies/index.md
      - AI: ai/docs/index.md